### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by skydig** [peacess/door_player#2]
make fail just like following
    --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\epaint-0.27.2\src\tessellator.rs
:1908:34
     |
1908 |         let stroke = Stroke::new(2.0, Color32::from_rgb(150, 255, 150));
     |                      ----------- ^^^ the trait `From<f64>` is not implemented for `f32`, which is required by `{f
loat}: Into<f32>`

**Comment by peacess** [comment]
more error info,   which code line in door player?

**Comment by peacess** [comment]
Long period without activity to close the issue
